"""
ACRCNN Learning Curve Analysis — uses real training logs exclusively.
Data source: learning_curve_real_data.json (generated by deep_learning_train_with_logging.py)
"""
import matplotlib.pyplot as plt
import numpy as np
import json
import os

LOG_FILE = "learning_curve_real_data.json"

# ================= 1. Load Data =================
if not os.path.exists(LOG_FILE):
    raise FileNotFoundError(f"{LOG_FILE} not found. Run deep_learning_train_with_logging.py first.")

with open(LOG_FILE, 'r') as f:
    data = json.load(f)
records = data["records"]
epochs = np.array([r["epoch"] for r in records])
train_loss = np.array([r["train_loss"] for r in records])
val_recall_all = np.array([r["val_recall"] for r in records])
val_recall_head = np.array([r["val_recall_head"] for r in records])
val_recall_tail = np.array([r["val_recall_tail"] for r in records])

# Convert recall from proportion to percentage
val_recall_head_pct = val_recall_head * 100
val_recall_tail_pct = val_recall_tail * 100
val_recall_all_pct = val_recall_all * 100

print(f"Loaded real training data: {len(records)} epochs, "
      f"head={data['head_classes']}, tail={data['tail_classes']}")

# ================= 2. Plot =================
fig, ax1 = plt.subplots(figsize=(8, 6), dpi=300)
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']

color_loss = '#1f77b4'
ax1.set_xlabel('Training Epochs', fontsize=14, fontweight='bold')
ax1.set_ylabel('Binary Cross Entropy (BCE) Loss', color=color_loss, fontsize=14, fontweight='bold')
ax1.plot(epochs, train_loss, color=color_loss, linestyle='-', marker='o', markersize=5, linewidth=2, label='Training Loss')
ax1.tick_params(axis='y', labelcolor=color_loss, labelsize=12)
ax1.tick_params(axis='x', labelsize=12)
ax1.grid(True, linestyle='--', alpha=0.5)

ax2 = ax1.twinx()
color_head = '#d62728'
color_all = '#2ca02c'
color_tail = '#7f7f7f'

ax2.set_ylabel('Validation Recall (%)', color='black', fontsize=14, fontweight='bold')
ax2.plot(epochs, val_recall_head_pct, color=color_head, linestyle='--', linewidth=2.5, label='Recall (Head Classes)')
ax2.plot(epochs, val_recall_all_pct, color=color_all, linestyle='-', linewidth=3, label='Global Micro-Recall')
ax2.plot(epochs, val_recall_tail_pct, color=color_tail, linestyle=':', linewidth=2.5, label='Recall (Tail Classes)')

# Dynamic y-axis range based on real data
y_max = max(np.max(val_recall_head_pct), np.max(val_recall_all_pct), np.max(val_recall_tail_pct)) * 1.2
y_max = max(y_max, 0.5)  # minimum readable range
ax2.set_ylim(0, y_max)

ax2.tick_params(axis='y', labelcolor='black', labelsize=12)

lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax2.get_legend_handles_labels()
ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='center right', fontsize=11, framealpha=0.9, edgecolor='black')

plt.title('Learning Dynamics of ACRCNN Baseline\n(Demonstrating the Representation Collapse under Long-Tailed Distribution)',
          fontsize=15, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig('learning_curve_analysis.pdf', format='pdf', bbox_inches='tight')
plt.savefig('learning_curve_analysis.png', format='png', dpi=300, bbox_inches='tight')
print("Chart saved: learning_curve_analysis.pdf (real data)")
